steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY_NAME}/triz-mcp-server:latest',
      './mcp-server'
    ]
    env: ['DOCKER_BUILDKIT=1']

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY_NAME}/triz-mcp-server:latest'

substitutions:
  _PROJECT_ID: 'lofty-advantage-501408-f9'
  _REGION: 'europe-west1'
  _REGISTRY_NAME: 'buildwithai-repo'

options:
  logging: CLOUD_LOGGING_ONLY
